name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/1 * * * *'  # Verifica a aplicação a cada minuto

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    - name: Start Flask app
      run: |
        nohup python app.py &
        sleep 10  # Aguarda 10 segundos para garantir que o servidor Flask esteja iniciado

    - name: Check if application is running
      run: |
        curl -sS http://localhost:5000 | grep 'Hello, World!'

    - name: Stop Flask app
      run: |
        pkill -f app.py
